#!/bin/bash
set -e
. ~/.profile
echo "start_solr:STARTING"
NAMED_PIPE_DIR=$GC_WIKIPEDIA_REPO_ROOT/named_pipes
IMPORT_FILE=$NAMED_PIPE_DIR/import.xml


cd $GC_WIKIPEDIA_REPO_ROOT
SOLR_HOME=$GC_WIKIPEDIA_REPO_ROOT/solr_home/solr




cd lib/solr/solr/example
echo "here" >> $SOLR_HOME/log.txt
java   -Xms512M -Xmx1024M  -Dsolr.solr.home=$SOLR_HOME -Dsolr.data.dir=$GC_WIKIPEDIA_SOLR_DATA_DIR -Dsolr.xmlInputFile=$IMPORT_FILE   -Dsolr.absolutePath=$SOLR_HOME  -jar start.jar >> $SOLR_HOME/log.txt


echo "start_solr:FINISHED"

