#!/bin/bash

. ~/.profile


cd $GC_WIKIPEDIA_REPO_ROOT
SOLR_HOME=$GC_WIKIPEDIA_REPO_ROOT/solr_home/solr

cd lib/solr/solr/example
echo "here" >> $SOLR_HOME/log.txt
java   -Xms512M -Xmx1024M  -Dsolr.solr.home=$SOLR_HOME  -Dsolr.absolutePath=$SOLR_HOME  -jar start.jar >> $SOLR_HOME/log.txt

#cd lib/solr/solr/example/; java   -Xms512M -Xmx1024M  -Dsolr.solr.home=../../../../solr_home/solr -Dsolr.absolutePath=`pwd`/../../../../solr_home/solr  -jar start.jar")
