#!/bin/bash
set -e
. ~/.profile
echo "index_100_000:STARTING"

$GC_WIKIPEDIA_REPO_ROOT/apps/reindex/index_base $GC_WIKIPEDIA_DL_DIR/first_100_000.xml

echo "the solr_server should take aproximately 40 minutes to complete this index"
echo "index_100_000:FINISHED"
