#!/bin/bash
. ~/.profile
NAMED_PIPE_DIR=$GC_WIKIPEDIA_REPO_ROOT_8984/named_pipes
IMPORT_FILE=$NAMED_PIPE_DIR/import.xml

mkdir $NAMED_PIPE_DIR
touch $IMPORT_FILE
rm $IMPORT_FILE
mkfifo $IMPORT_FILE
# 500
#nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2 | head -n  107296 >  $GC_WIKIPEDIA_DL_DIR/import.xml &
#100k
#nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2 | head -n  5577937 >  $GC_WIKIPEDIA_DL_DIR/import.xml &

#nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2 | head -n  1577937 >  $GC_WIKIPEDIA_DL_DIR/import.xml &
nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR_8984/enwiki-latest-pages-articles.xml.bz2  >  $IMPORT_FILE &



cd $GC_WIKIPEDIA_REPO_ROOT/apps/reindex
curl "http://localhost:8984/solr/dataimport?command=full-import" 
sleep 50



