#!/bin/bash
. ~/.profile
echo "index_all:STARTING"
NAMED_PIPE_DIR=$GC_WIKIPEDIA_REPO_ROOT/named_pipes
IMPORT_FILE=$NAMED_PIPE_DIR/import.xml

mkdir $NAMED_PIPE_DIR
touch $IMPORT_FILE
rm $IMPORT_FILE
mkfifo $IMPORT_FILE
nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2  >  $IMPORT_FILE &



cd $GC_WIKIPEDIA_REPO_ROOT/apps/reindex
./trigger_reimport



echo "index_all:FINISHED"
