#!/bin/bash
. ~/.profile

rm $GC_WIKIPEDIA_DL_DIR/import.xml
mkfifo $GC_WIKIPEDIA_DL_DIR/import.xml
nohup bunzip2 -c  $GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2 | head -n 107296 >  $GC_WIKIPEDIA_DL_DIR/import.xml &



cd $GC_WIKIPEDIA_REPO_ROOT/apps/reindex
./trigger_reimport



