#!/bin/bash


curl "http://localhost:8983/solr/dataimport?command=full-import" 

echo "the index has been triggered, but not necessarily completed"
echo "read the indexing_apps section of the readme for more information about progress tracking"
