#!/bin/bash

. ~/.profile
mkdir $GC_WIKIPEDIA_DL_DIR

nohup curl http://download.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2 >$GC_WIKIPEDIA_DL_DIR/enwiki-latest-pages-articles.xml.bz2


