#!/bin/bash
set -e
. ~/.profile


cd $GC_WIKIPEDIA_REPO_ROOT
cd lib/solr/solr/
ant clean compile example

cd $GC_WIKIPEDIA_REPO_ROOT
cd solr_home/Wikipedia_importer/wikipedia_solr 
ant clean compile jar

cd $GC_WIKIPEDIA_REPO_ROOT
cd apps/update
./recompile_apps
