#!/bin/bash
set -e
. ~/.profile

echo "recompile_apps:STARTING"
compile_app ()
{
touch  $1.app
rm -rf $1.app
$GC_WIKIPEDIA_REPO_ROOT/apps/appify  $1

touch $GC_WIKIPEDIA_REPO_ROOT/apps/$1.app
rm -rf $GC_WIKIPEDIA_REPO_ROOT/apps/$1.app
mv $1.app $GC_WIKIPEDIA_REPO_ROOT/apps/
}







cd $GC_WIKIPEDIA_REPO_ROOT
cd apps/update


U=$GC_WIKIPEDIA_REPO_ROOT/apps/update
rm -rf $U/recompile_apps_wrap.app

cd $GC_WIKIPEDIA_REPO_ROOT/apps/reindex
touch  index_1000_wrap.app
rm -rf index_1000_wrap.app



cd $GC_WIKIPEDIA_REPO_ROOT/apps/wrappers

compile_app start_solr

compile_app update_all
compile_app git_update
compile_app download_dump
compile_app make_helper_files

compile_app index_1_000
compile_app index_10_000
compile_app index_100_000
compile_app index_all

echo "recompile_apps:FINISHED"
